### ISSUE TITLE
Error in browseURL(url) : 'url' must be a non-empty character string

### ISSUE THREAD

**Issue by RubenVezzoli** [jburkhardt/RBingAds#26]
Hi I'm trying to access the API using your package but somehow it doesn't work. Below you can find my code, I get an error message:

_Error in browseURL(url) : 'url' must be a non-empty character string_

```
library(RBingAds)

bing_auth <- authenticate(save = F,
                          path = ".bing.auth.RData",
                          gitignore = F)
```
It think that there is something wrong in my .bing.auth.RData file but I cannot figure out what.  I wasn't sure about how to pass the information (dataframe, list or something else). Right now, I'm using a list:

```
credentials <- list(
  
  client_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  client_secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  username = "john.doe@company.com",
  password = "xxxxxxxxxxxxxxxxxxxxxxxxxx",
  developer_token = "xxxxxxxxxxxxxxxxxxxxxxxxxx",
  account_id = "xxxxxxxxxx"
)
```

Is it correct?

Thanks in advance! 👍

**Comment by jburkhardt** [comment]
Hi @RubenVezzoli 
Thank you for using the package! You don´t need to save your credentials in a list in advance. The function `authenticate` takes care of this. You just run `authenticate()` and enter your credentials in the R prompt. During the authentication browser, your web browser should pop up for a one time authentication. Does this work for you?
