### ISSUE TITLE
R CMD check: Notes

### ISSUE THREAD

**Issue by jburkhardt** [jburkhardt/RBingAds#6]
.get_columns_xml: no visible binding for global variable ‘columns’
  .load_token: no visible global function definition for ‘add_headers’
  .refresh_token: no visible global function definition for ‘add_headers’
  download_data: no visible global function definition for ‘zip’
  download_data: no visible global function definition for
    ‘download.file’
  download_data: no visible global function definition for ‘unzip’
  download_data: no visible global function definition for ‘read.csv’
  get_report_id: no visible binding for global variable ‘columms’
  Undefined global functions or variables:
    add_headers columms columns download.file read.csv unzip zip
  Consider adding
    importFrom("utils", "download.file", "read.csv", "unzip", "zip")
  to your NAMESPACE file.

**Comment by jburkhardt** [comment]
.get_columns_xml: no visible binding for global variable ‘columns’
  .load_token: no visible global function definition for ‘add_headers’
  .refresh_token: no visible global function definition for ‘add_headers’
  get_report_id: no visible binding for global variable ‘columms’
  Undefined global functions or variables:
    add_headers columms columns

**Comment by Nelson-Gon** [comment]
Is it ok if I take a look at these issues?

**Comment by jburkhardt** [comment]
@Nelson-Gon I appreciate your help! Thank you! I already fixed this issue locally.
